server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx:3306/collect_db?characterEncoding=UTF-8&useSSL=false
    username: root
    password: xxx
  mail:
    host: smtp.qq.com
    username: 2856296647@qq.com
    password: mjvtvhfrfdqcdehj
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

collect:
  work:
    root-path: /root/collect/work/
    url-path: /work/

